---
title: "Michele Claibourn's Resume"
author: Michele Claibourn
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_resume.css', 'styles.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("resume_printing_functions.R")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1nL_I7JWzutRehfgZ0uRmQzn_xrKd8AeDFVLvaV_s3cg/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
# datadrivencv::build_network_logo(CV$entries_data)
```

See full CV and project portfolio at [mclaibourn.github.io](https://mclaibourn.github.io/).

Main
================================================================================

Michele Claibourn {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```


Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('professional_experience_aside')
```
:::

```{r}
CV %<>% print_section('professional_positions')
```


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```


Teaching and Mentoring {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('teaching')
```


Selected Writing and Presentations {data-icon=book}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('skills_aside')
```
:::

```{r}
CV %<>% print_section('report_writing')
```

```{r}
CV %<>% print_section('presentation')
```

::: aside
```{r}
CV %<>% print_text_block('teaching_experience_aside')
```
:::

```{r}
CV %<>% print_section('academic_articles')
```


```{r}
CV %<>% print_links()
```
