---
title: "Michele Claibourn's CV"
author: Michele Claibourn
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("CV_printing_functions.R")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1nL_I7JWzutRehfgZ0uRmQzn_xrKd8AeDFVLvaV_s3cg/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```

```{r}
if(params$pdf_mode){
  cat("View this CV online with links at _mclaibourn.github.io/mpc_cv_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/mclaibourn/mpc_cv/raw/master/mpc_cv.pdf)")
}
```

See my [webpage](https://mclaibourn.github.io/) for a more project-oriented portfolio.


Main
================================================================================

Michele Claibourn {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```


Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('professional_experience_aside')
```
<br>
<br>
<br>
Last updated on `r Sys.Date()`.
:::

```{r}
CV %<>% print_section('professional_positions')
```

<!-- These breaks just force a new page so section doesnt get cut off -->
<br>


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```



Teaching and Mentoring {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('teaching_experience_aside')
```
:::

```{r}
CV %<>% print_section('teaching')
```


Publications {data-icon=book}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('skills_aside')
```
<br>
<br>
<br>
The source code is available [on github.com/mclaibourn/mpc_cv](https://github.com/mclaibourn/mpc_cv).
:::

```{r}
CV %<>% print_section('academic_articles')
```


Reports and Selected Writing {data-icon=chart-line}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('report_writing')
```


Grants and Awards {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('grant_award')
```


Professional Activities and Service {data-icon=user-friends}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('service')
```


Recent Presentations {data-icon=chalkboard}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('presentation')
```



```{r}
CV %<>% print_links()
```
